### ISSUE TITLE
Enable Org-Wide Workflows

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-documentation#115]
In early 2023, GitHub [opened their 'org-wide workflows' feature to beta testers](https://github.blog/changelog/2023-01-10-github-actions-support-for-organization-wide-required-workflows-public-beta/). It is now no longer available for testing 😢

This would enable us to store all `brightway-documentation`-related workflow `.yaml` files in a single directory (eg. [`brightway-documentation/.github/workflows`](https://github.com/brightway-lca/brightway-documentation/tree/main/.github/workflows)) and simply "enable" them for other repositories (eg. `bw2io`, `bw2data`, etc.) in the repository settings:

![211551996-c32d315d-e9a5-47fd-b74b-7263773ce77a](https://github.com/brightway-lca/brightway-documentation/assets/23102087/f2cc4e92-93e1-4e4a-ba77-cd057154793f)

This does not add new functionality, but will de-duplicate the workflow files and improve consistency.

See also my discussion in the GitHub Actions repo: https://github.com/github/docs/discussions/24018#discussioncomment-5966058

**Comment by michaelweinold** [comment]
After re-inspecting the documentation for Required Workflows, it has become clear that these are intended primarily to

> (...) implement organization-wide CI/CD policies that apply to current and future repositories. A required workflow is triggered by pull_request and pull_request_target default events and appears as a required status check, which blocks the ability to merge the pull request until the required workflow succeeds.

This does not make sense in the case of a workflow that triggers a `git submodule pull`. However, we are now using _reusable workflows_. All repos included as submodules in the `brightway-documentation` repo use [this simple reusable workflow](https://github.com/brightway-lca/brightway-documentation/blob/main/.github/workflows/github_action_trigger_submodule_pull_reusable.yml):

```
# this workflow re-uses the workflow 'github_action_trigger_submodule_pull_main.yml' in the brightway-documentation repository
name: Create Workflow Dispatch (Trigger Submodule Pull), Re-Use Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    re-use_workflow:
      uses:
        brightway-lca/brightway-documentation/.github/workflows/github_action_trigger_submodule_pull_main.yml@main
      secrets: inherit # https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-secrets-to-nested-workflows
```
