### ISSUE TITLE
Update GitHub Actions Workflows from Bash to GitHub CLI

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/brightway-documentation#77]
...inspired by [this conversation](https://github.com/orgs/community/discussions/26323#discussioncomment-5600001), the current workflows should be updated to use the much simpler, better readable GitHub CLI functions:

Something like

```
steps:
  - run: |
      gh workflow run workflow.yml -R org/repo
env:
  GH_TOKEN: ${{ secrets.MY_TOKEN }}
```

could replace

```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GHA_WORKFLOW_TRIGGER }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'brightway-lca',
              repo: 'brightway-documentation',
              workflow_id: 'github_action_update_submodules.yml',
              ref: 'main',
            })
```
